micronaut:
  application:
    name: fretesRest

grpc:
  client:
    plaintext: true
    max-retry-attempts: 10
  channels:
    fretes:
      address: '0.0.0.0:50051' #'localhost:50051'
      plaintext: true
      max-retry-attempts: 10
